BEGIN;
CREATE TABLE "Website_capacitacaoexterna" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "custo" varchar(100) NOT NULL, "palestrante" varchar(100) NOT NULL);
CREATE TABLE "Website_capacitacaointerna" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "data" date NOT NULL, "material" varchar(200) NOT NULL);
CREATE TABLE "Website_contatocapacitacao" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "contatos" varchar(500) NOT NULL, "capacitacaoExterna_id" integer NOT NULL REFERENCES "Website_capacitacaoexterna" ("id"));
CREATE TABLE "Website_contatoiniciativa" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "contatos" varchar(500) NOT NULL);
CREATE TABLE "Website_empresaparceira" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(100) NOT NULL, "ramoAtuacao" varchar(100) NOT NULL, "background" varchar(100) NOT NULL, "apoios" varchar(100) NOT NULL, "propostaApoio" varchar(100) NOT NULL);
CREATE TABLE "Website_evento" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(100) NOT NULL, "data" date NOT NULL, "feedback" varchar(500) NOT NULL);
CREATE TABLE "Website_eventoinstitucional" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "custo" varchar(100) NOT NULL, "mostivoPatrocinio" varchar(500) NOT NULL, "evento_id" integer NOT NULL REFERENCES "Website_evento" ("id"));
CREATE TABLE "Website_eventoinstitucional_empresasParceiras" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "eventoinstitucional_id" integer NOT NULL REFERENCES "Website_eventoinstitucional" ("id"), "empresaparceira_id" integer NOT NULL REFERENCES "Website_empresaparceira" ("id"), UNIQUE ("eventoinstitucional_id", "empresaparceira_id"));
CREATE TABLE "Website_financiamento" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(100) NOT NULL, "processo" varchar(100) NOT NULL, "tema" varchar(100) NOT NULL, "projetos" varchar(100) NOT NULL, "valor" varchar(100) NOT NULL, "prazos" varchar(100) NOT NULL, "instituicaoResponsavel" varchar(100) NOT NULL, "vencedoresAnteriores" varchar(500) NOT NULL);
CREATE TABLE "Website_iniciativa" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(100) NOT NULL, "data" date NOT NULL, "tipoMembro" varchar(100) NOT NULL, "publicoAlvo" varchar(100) NOT NULL, "duracao" varchar(100) NOT NULL, "questoesChaves" varchar(500) NOT NULL, "areaAtuacao" varchar(100) NOT NULL, "anoFundacao" integer NOT NULL, "website" varchar(100) NOT NULL, "parceiros" varchar(500) NOT NULL, "principaisProgramas" varchar(500) NOT NULL, "apoio" varchar(100) NOT NULL, "percepcaoPresenca" varchar(100) NOT NULL, "Realizada" bool NOT NULL);
CREATE TABLE "Website_membro" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(100) NOT NULL, "email" varchar(75) NOT NULL);
CREATE TABLE "Website_membro_eventos" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "membro_id" integer NOT NULL REFERENCES "Website_membro" ("id"), "evento_id" integer NOT NULL REFERENCES "Website_evento" ("id"), UNIQUE ("membro_id", "evento_id"));
CREATE TABLE "Website_setor" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(100) NOT NULL, "Permissao" varchar(150) NOT NULL);
CREATE TABLE "Website_telefone" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "telefone" varchar(128) NOT NULL UNIQUE, "membro_id" integer NOT NULL REFERENCES "Website_membro" ("id"));
CREATE TABLE "Website_tipoparceria" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(100) NOT NULL);
CREATE TABLE "Website_membro__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(100) NOT NULL, "email" varchar(75) NOT NULL, "setor_id" integer NOT NULL REFERENCES "Website_setor" ("id"));
INSERT INTO "Website_membro__new" ("email", "setor_id", "id", "nome") SELECT "email", NULL, "id", "nome" FROM "Website_membro";
DROP TABLE "Website_membro";
ALTER TABLE "Website_membro__new" RENAME TO "Website_membro";
CREATE INDEX Website_contatocapacitacao_6247a40e ON "Website_contatocapacitacao" ("capacitacaoExterna_id");
CREATE INDEX Website_eventoinstitucional_afb29da0 ON "Website_eventoinstitucional" ("evento_id");
CREATE INDEX Website_eventoinstitucional_empresasParceiras_0b94a609 ON "Website_eventoinstitucional_empresasParceiras" ("eventoinstitucional_id");
CREATE INDEX Website_eventoinstitucional_empresasParceiras_97e6e538 ON "Website_eventoinstitucional_empresasParceiras" ("empresaparceira_id");
CREATE INDEX Website_telefone_1c222141 ON "Website_telefone" ("membro_id");
CREATE INDEX Website_membro_90f89678 ON "Website_membro" ("setor_id");
CREATE TABLE "Website_membro__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(100) NOT NULL, "email" varchar(75) NOT NULL, "setor_id" integer NOT NULL REFERENCES "Website_setor" ("id"), "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id"));
INSERT INTO "Website_membro__new" ("email", "setor_id", "id", "nome") SELECT "email", "setor_id", "id", "nome" FROM "Website_membro";
DROP TABLE "Website_membro";
ALTER TABLE "Website_membro__new" RENAME TO "Website_membro";
CREATE INDEX Website_membro_90f89678 ON "Website_membro" ("setor_id");
CREATE TABLE "Website_iniciativa__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(100) NOT NULL, "data" date NOT NULL, "tipoMembro" varchar(100) NOT NULL, "publicoAlvo" varchar(100) NOT NULL, "duracao" varchar(100) NOT NULL, "questoesChaves" varchar(500) NOT NULL, "areaAtuacao" varchar(100) NOT NULL, "anoFundacao" integer NOT NULL, "website" varchar(100) NOT NULL, "parceiros" varchar(500) NOT NULL, "principaisProgramas" varchar(500) NOT NULL, "apoio" varchar(100) NOT NULL, "percepcaoPresenca" varchar(100) NOT NULL, "Realizada" bool NOT NULL, "membro_id" integer NOT NULL REFERENCES "Website_membro" ("id"));
INSERT INTO "Website_iniciativa__new" ("website", "apoio", "percepcaoPresenca", "publicoAlvo", "duracao", "nome", "Realizada", "principaisProgramas", "anoFundacao", "tipoMembro", "parceiros", "questoesChaves", "data", "id", "areaAtuacao", "membro_id") SELECT "website", "apoio", "percepcaoPresenca", "publicoAlvo", "duracao", "nome", "Realizada", "principaisProgramas", "anoFundacao", "tipoMembro", "parceiros", "questoesChaves", "data", "id", "areaAtuacao", NULL FROM "Website_iniciativa";
DROP TABLE "Website_iniciativa";
ALTER TABLE "Website_iniciativa__new" RENAME TO "Website_iniciativa";
CREATE INDEX Website_iniciativa_1c222141 ON "Website_iniciativa" ("membro_id");
CREATE TABLE "Website_financiamento__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(100) NOT NULL, "processo" varchar(100) NOT NULL, "tema" varchar(100) NOT NULL, "projetos" varchar(100) NOT NULL, "valor" varchar(100) NOT NULL, "prazos" varchar(100) NOT NULL, "instituicaoResponsavel" varchar(100) NOT NULL, "vencedoresAnteriores" varchar(500) NOT NULL, "membro_id" integer NOT NULL REFERENCES "Website_membro" ("id"));
INSERT INTO "Website_financiamento__new" ("instituicaoResponsavel", "vencedoresAnteriores", "nome", "processo", "tema", "prazos", "valor", "projetos", "id", "membro_id") SELECT "instituicaoResponsavel", "vencedoresAnteriores", "nome", "processo", "tema", "prazos", "valor", "projetos", "id", NULL FROM "Website_financiamento";
DROP TABLE "Website_financiamento";
ALTER TABLE "Website_financiamento__new" RENAME TO "Website_financiamento";
CREATE INDEX Website_financiamento_1c222141 ON "Website_financiamento" ("membro_id");
CREATE TABLE "Website_empresaparceira_iniciativas" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "empresaparceira_id" integer NOT NULL REFERENCES "Website_empresaparceira" ("id"), "iniciativa_id" integer NOT NULL REFERENCES "Website_iniciativa" ("id"), UNIQUE ("empresaparceira_id", "iniciativa_id"));
CREATE TABLE "Website_empresaparceira__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(100) NOT NULL, "ramoAtuacao" varchar(100) NOT NULL, "background" varchar(100) NOT NULL, "apoios" varchar(100) NOT NULL, "propostaApoio" varchar(100) NOT NULL, "tipoParceria_id" integer NOT NULL REFERENCES "Website_tipoparceria" ("id"));
INSERT INTO "Website_empresaparceira__new" ("ramoAtuacao", "nome", "propostaApoio", "tipoParceria_id", "background", "id", "apoios") SELECT "ramoAtuacao", "nome", "propostaApoio", NULL, "background", "id", "apoios" FROM "Website_empresaparceira";
DROP TABLE "Website_empresaparceira";
ALTER TABLE "Website_empresaparceira__new" RENAME TO "Website_empresaparceira";
CREATE INDEX Website_empresaparceira_e85c5673 ON "Website_empresaparceira" ("tipoParceria_id");
CREATE TABLE "Website_contatoiniciativa__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "contatos" varchar(500) NOT NULL, "iniciativa_id" integer NOT NULL REFERENCES "Website_iniciativa" ("id"));
INSERT INTO "Website_contatoiniciativa__new" ("id", "iniciativa_id", "contatos") SELECT "id", NULL, "contatos" FROM "Website_contatoiniciativa";
DROP TABLE "Website_contatoiniciativa";
ALTER TABLE "Website_contatoiniciativa__new" RENAME TO "Website_contatoiniciativa";
CREATE INDEX Website_contatoiniciativa_d89c76dd ON "Website_contatoiniciativa" ("iniciativa_id");
CREATE TABLE "Website_capacitacaointerna__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "data" date NOT NULL, "material" varchar(200) NOT NULL, "evento_id" integer NOT NULL REFERENCES "Website_evento" ("id"));
INSERT INTO "Website_capacitacaointerna__new" ("evento_id", "material", "data", "id") SELECT NULL, "material", "data", "id" FROM "Website_capacitacaointerna";
DROP TABLE "Website_capacitacaointerna";
ALTER TABLE "Website_capacitacaointerna__new" RENAME TO "Website_capacitacaointerna";
CREATE INDEX Website_capacitacaointerna_afb29da0 ON "Website_capacitacaointerna" ("evento_id");
CREATE TABLE "Website_capacitacaoexterna__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "custo" varchar(100) NOT NULL, "palestrante" varchar(100) NOT NULL, "evento_id" integer NOT NULL REFERENCES "Website_evento" ("id"));
INSERT INTO "Website_capacitacaoexterna__new" ("evento_id", "custo", "id", "palestrante") SELECT NULL, "custo", "id", "palestrante" FROM "Website_capacitacaoexterna";
DROP TABLE "Website_capacitacaoexterna";
ALTER TABLE "Website_capacitacaoexterna__new" RENAME TO "Website_capacitacaoexterna";
CREATE INDEX Website_capacitacaoexterna_afb29da0 ON "Website_capacitacaoexterna" ("evento_id");